In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, OrdinalEncoder
from sklearn.model_selection import train_test_split
# import kagglehub
import shutil
import os
# Download latest version
# path = kagglehub.dataset_download("dinithpriyankara/research-dataset")

# print("Path to dataset files:", path)

# destination_path = "/content"
# if os.path.exists(path):
#     try:
#         shutil.copytree(path, destination_path + "/research-dataset", dirs_exist_ok = True)
#         print("Files copied successfully to:", destination_path + "/research-dataset")
#     except Exception as e:
#         print(f"Error copying files: {e}")
# else:
#     print(f"Source directory not found: {source_path}")

In [2]:
url = "Steel_industry_data.csv"
df_old = pd.read_csv(url)
df_old.head()

,date,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_of_week,Load_Type
0,01/01/2018 00:15,3.17,2.95,0.0,0.0,73.21,100.0,900,Weekday,Monday,Light_Load
1,01/01/2018 00:30,4.00,4.46,0.0,0.0,66.77,100.0,1800,Weekday,Monday,Light_Load
2,01/01/2018 00:45,3.24,3.28,0.0,0.0,70.28,100.0,2700,Weekday,Monday,Light_Load
3,01/01/2018 01:00,3.31,3.56,0.0,0.0,68.09,100.0,3600,Weekday,Monday,Light_Load
4,01/01/2018 01:15,3.82,4.50,0.0,0.0,64.72,100.0,4500,Weekday,Monday,Light_Load

In [3]:
encoder = OrdinalEncoder()
df_old[['WeekStatus', 'Load_Type']] = encoder.fit_transform(df_old[['WeekStatus', 'Load_Type']])

In [4]:
df_old.head()

,date,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_of_week,Load_Type
0,01/01/2018 00:15,3.17,2.95,0.0,0.0,73.21,100.0,900,0.0,Monday,0.0
1,01/01/2018 00:30,4.00,4.46,0.0,0.0,66.77,100.0,1800,0.0,Monday,0.0
2,01/01/2018 00:45,3.24,3.28,0.0,0.0,70.28,100.0,2700,0.0,Monday,0.0
3,01/01/2018 01:00,3.31,3.56,0.0,0.0,68.09,100.0,3600,0.0,Monday,0.0
4,01/01/2018 01:15,3.82,4.50,0.0,0.0,64.72,100.0,4500,0.0,Monday,0.0

In [7]:
df_old['date'] = pd.to_datetime(df_old['date'], dayfirst=True)

In [8]:
df_old.head()

,date,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_of_week,Load_Type
0,2018-01-01 00:15:00,3.17,2.95,0.0,0.0,73.21,100.0,900,0.0,Monday,0.0
1,2018-01-01 00:30:00,4.00,4.46,0.0,0.0,66.77,100.0,1800,0.0,Monday,0.0
2,2018-01-01 00:45:00,3.24,3.28,0.0,0.0,70.28,100.0,2700,0.0,Monday,0.0
3,2018-01-01 01:00:00,3.31,3.56,0.0,0.0,68.09,100.0,3600,0.0,Monday,0.0
4,2018-01-01 01:15:00,3.82,4.50,0.0,0.0,64.72,100.0,4500,0.0,Monday,0.0

In [9]:
fet=df_old.columns

In [10]:
fet

Index(['date', 'Usage_kWh', 'Lagging_Current_Reactive.Power_kVarh',
       'Leading_Current_Reactive_Power_kVarh', 'CO2(tCO2)',
       'Lagging_Current_Power_Factor', 'Leading_Current_Power_Factor', 'NSM',
       'WeekStatus', 'Day_of_week', 'Load_Type'],
      dtype='object')

In [12]:
df_old=df_old.drop(columns=["Day_of_week"])

In [13]:
df_old.columns

Index(['date', 'Usage_kWh', 'Lagging_Current_Reactive.Power_kVarh',
       'Leading_Current_Reactive_Power_kVarh', 'CO2(tCO2)',
       'Lagging_Current_Power_Factor', 'Leading_Current_Power_Factor', 'NSM',
       'WeekStatus', 'Load_Type'],
      dtype='object')

In [14]:
df_old.to_csv("steel_industry_data_preprocessed_v1.csv", index=False)

loading the dataset again

In [19]:
df_new=pd.read_csv("steel_industry_data_preprocessed_v1.csv")

In [23]:
df_new.head()

,date,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Load_Type
0,2018-01-01 00:15:00,3.17,2.95,0.0,0.0,73.21,100.0,900,0.0,0.0
1,2018-01-01 00:30:00,4.00,4.46,0.0,0.0,66.77,100.0,1800,0.0,0.0
2,2018-01-01 00:45:00,3.24,3.28,0.0,0.0,70.28,100.0,2700,0.0,0.0
3,2018-01-01 01:00:00,3.31,3.56,0.0,0.0,68.09,100.0,3600,0.0,0.0
4,2018-01-01 01:15:00,3.82,4.50,0.0,0.0,64.72,100.0,4500,0.0,0.0

In [24]:
df_new.columns

Index(['date', 'Usage_kWh', 'Lagging_Current_Reactive.Power_kVarh',
       'Leading_Current_Reactive_Power_kVarh', 'CO2(tCO2)',
       'Lagging_Current_Power_Factor', 'Leading_Current_Power_Factor', 'NSM',
       'WeekStatus', 'Load_Type'],
      dtype='object')

without downsampling

In [26]:
df_new.set_index('date', inplace=True)

In [28]:
df_new.head()

,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Load_Type
date,,,,,,,,,
2018-01-01 00:15:00,3.17,2.95,0.0,0.0,73.21,100.0,900,0.0,0.0
2018-01-01 00:30:00,4.00,4.46,0.0,0.0,66.77,100.0,1800,0.0,0.0
2018-01-01 00:45:00,3.24,3.28,0.0,0.0,70.28,100.0,2700,0.0,0.0
2018-01-01 01:00:00,3.31,3.56,0.0,0.0,68.09,100.0,3600,0.0,0.0
2018-01-01 01:15:00,3.82,4.50,0.0,0.0,64.72,100.0,4500,0.0,0.0

In [29]:
import matplotlib.pyplot as plt
import seaborn as sns